openapi: 3.0.2
info:
  title: Access Pass
  description: "Application de generation de pass d'accès utilisant le design pattern producer/consumer"
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
paths:
  /accessPass:
    post:
      summary: Request for a access pass
      operationId: postAccessPassRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestDto'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessPassList'
        404:
          description: Not Found
          content: {}
        415:
          description: Erreur dans le payload, il doit être obligatoire
          content: {}
components:
  schemas:
    AccessPassBasicInfo:
      properties:
        username:
          type: string
        firstName:
          type: string
        birthDate:
          type: string
          example:
            10-01-1990
        isVIP:
          type: boolean
    RequestDto:
      type: object
      properties:
        basicInfo:
          type: object
          $ref: '#/components/schemas/AccessPassBasicInfo'
    AccessPassList:
      type: array
      items:
        $ref: '#/components/schemas/AccessPass'
    AccessPass:
      type: object
      properties:
        basicInfo:
          type: object
          $ref: '#/components/schemas/AccessPassBasicInfo'
        dateDemande:
          type: string
          example:
            21-02-2022_21-37
        dateGeneration:
          type: string
          example:
            21-02-2022_21-42
        codeValue:
          type: string